### ISSUE TITLE
Game.Player.Ped.GetLastWeaponImpactCoords() is not returning correct coords

### ISSUE THREAD

**Issue by leonard2z** [Halen84/ScriptHookRDR2DotNet-V2#6] opened 2023-05-30 15:59 UTC
The Y axis value is always 0.

**Comment by Halen84** [comment] 2023-05-31 00:37
This is caused by `Vector3` not having correct alignment. This will be fixed in the next update. Thanks

**Closed by Halen84** 2023-05-31 00:37 UTC
